=== simobe-git/tes/dtd/avatar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT utenti (utente+)>
<!ELEMENT utente (username, avatar)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT avatar (#PCDATA)>

=== simobe-git/tes/xml/avatar.xml
<?xml version="1.0"?>
<!DOCTYPE utenti SYSTEM "../dtd/avatar.dtd">
<utenti>
  <utente>
    <username>admin1</username>
    <avatar>default_avatar.jpg</avatar>
  </utente>
  <utente>
    <username>gestore1</username>
    <avatar>default_avatar.jpg</avatar>
  </utente>
  <utente>
    <username>cliente1</username>
    <avatar>stack.png</avatar>
  </utente>
  <utente>
    <username>cliente2</username>
    <avatar>default_avatar.jpg</avatar>
  </utente>
  <utente>
    <username>cliente3</username>
    <avatar>avatar2.jpg</avatar>
  </utente>
  <utente>
    <username>gestore2</username>
    <avatar>avatar3.jpg</avatar>
  </utente>
  <utente>
    <username>cliente4</username>
    <avatar>stack.png</avatar>
  </utente>
</utenti>
