=== simobe-git/tes/dtd/faq.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT faqs (faq+)>
<!ELEMENT faq (domanda, risposta, data_creazione, fonte)>
<!ELEMENT domanda (#PCDATA)>
<!ELEMENT risposta (#PCDATA)>
<!ELEMENT data_creazione (#PCDATA)>
<!ELEMENT fonte (#PCDATA)>
<!ATTLIST faq id CDATA #REQUIRED>

=== simobe-git/tes/xml/faq.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE faqs SYSTEM "../dtd/faq.dtd">
<faqs>
  <faq id="2">
    <domanda>Come funziona il sistema di sconti?</domanda>
    <risposta>Gli sconti si applicano automaticamente in base alla tua reputazione e/o ai crediti spesi!</risposta>
    <data_creazione>2024-03-15</data_creazione>
    <fonte>admin</fonte>
  </faq>
  <faq id="3">
    <domanda>Come posso acquistare un gioco?</domanda>
    <risposta>Aggiungi il gioco al carrello, poi procedi al checkout con i tuoi crediti.</risposta>
    <data_creazione>2024-03-15</data_creazione>
    <fonte>admin</fonte>
  </faq>
  <faq id="4">
    <domanda>Dove posso trovare i contatti?</domanda>
    <risposta>Puoi trovare i contatti nell'apposita sezione a cui puoi accedere dal menù della homepage.</risposta>
    <data_creazione>2024-03-15</data_creazione>
    <fonte>admin</fonte>
  </faq>
  <faq id="5">
    <domanda>Quanto tempo ci vuole per ricevere il gioco?</domanda>
    <risposta>I giochi digitali sono disponibili immediatamente dopo l'acquisto.</risposta>
    <data_creazione>2024-03-15</data_creazione>
    <fonte>forum</fonte>
  </faq>
  <faq id="6">
    <domanda>Gli sconti sono cumulabili?</domanda>
    <risposta>Si, gli sconti sono cumulabili. Se ne hai diritto, puoi trovare più sconti applicati sui giochi.</risposta>
    <data_creazione>2024-03-15</data_creazione>
    <fonte>admin</fonte>
  </faq>
  <faq id="7">
    <domanda>Come funziona il sistema di recensioni?</domanda>
    <risposta>Puoi recensire i giochi che hai acquistato e valutare le recensioni di altri utenti, ma solo dopo aver effettuato il login.</risposta>
    <data_creazione>2024-03-15</data_creazione>
    <fonte>admin</fonte>
  </faq>
  <faq id="8">
    <domanda>Posso regalare crediti ad altri utenti?</domanda>
    <risposta>No, i crediti sono personali e non trasferibili.</risposta>
    <data_creazione>2024-03-15</data_creazione>
    <fonte>admin</fonte>
  </faq>
  <faq id="9">
    <domanda>Come funzionano i bonus?</domanda>
    <risposta>I bonus sono crediti extra che ricevi in omaggio acquistando giochi per un prezzo complessivo maggiore o uguale a 50 crediti. In tal caso, riceverai 5 crediti in omaggio</risposta>
    <data_creazione>2024-03-15</data_creazione>
    <fonte>forum</fonte>
  </faq>
  <faq id="10">
    <domanda>Cosa sono gli sconti?</domanda>
    <risposta>Gli sconti vengono applicati in base a vari criteri, e sono calcolati automaticamente dal sistema mentre acquisti dei giochi</risposta>
    <data_creazione>2024-04-12</data_creazione>
    <fonte>forum</fonte>
  </faq>
  <faq id="11">
    <domanda>Che tipi di sconti esistono?</domanda>
    <risposta>Ci sono varie tipologie di sconti: sconti applicati dopo aver speso un determinato numero di crediti; sconti per aver speso crediti in un determinato periodo temporale; sconti per clienti che hanno una determinata reputazione; sconti che sono registrati nel sistema da un determinato numero di mesi
    </risposta>
    <data_creazione>2024-04-19</data_creazione>
    <fonte>forum</fonte>
  </faq>
  <faq id="12">
    <domanda>Consigliereste di giocare ad un ragazzo di 13 anni?</domanda>
    <risposta>Nell'età minima viene consigliato almeno 14 anni, per cui direi di aspettare!</risposta>
    <data_creazione>2025-06-10</data_creazione>
    <fonte>forum</fonte>
  </faq>
  <faq id="13">
    <domanda>Cosa accade se siamo più di 6 giocatori?</domanda>
    <risposta>Probabilmente i soldi da distribuire a tutti i giocatori non basteranno e, quasi sicuramente, qualche giocatore si troverà pochissime proprietà in suo possesso.</risposta>
    <data_creazione>2025-06-10</data_creazione>
    <fonte>forum</fonte>
  </faq>
  <faq id="1749647925">
    <domanda>Sono indeciso se comprarlo o no: vi è piaciuto? cosa vi ha soddisfatto e cosa non? voglio chiarirmi le idee per decidere se acquistarlo</domanda>
    <risposta>risposta4 pasquetta</risposta>
    <data_creazione>2025-06-11</data_creazione>
    <fonte>forum</fonte>
  </faq>
</faqs>
