=== simobe-git/tes/dtd/recensioni.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT recensioni (recensione*)>
<!ELEMENT recensione (username, codice_gioco, testo, data, giudizi*)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT codice_gioco (#PCDATA)>
<!ELEMENT testo (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT giudizi (giudizio*)>
<!ELEMENT giudizio (username_votante, stelle)>
<!ELEMENT username_votante (#PCDATA)>
<!ELEMENT stelle (#PCDATA)>
<!ATTLIST recensione id CDATA #REQUIRED>

=== simobe-git/tes/xml/recensioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recensioni SYSTEM "../dtd/recensioni.dtd">
<recensioni>
  <recensione id="1">
    <username>cliente1</username>
    <codice_gioco>1</codice_gioco>
    <testo>Ottimo gioco, grafica spettacolare e gameplay coinvolgente!</testo>
    <data>2024-03-15</data>
    <giudizi>
      <giudizio>
        <username_votante>cliente2</username_votante>
        <stelle>4</stelle>
      </giudizio>
      <giudizio>
        <username_votante>cliente1</username_votante>
        <stelle>4</stelle>
      </giudizio>
    </giudizi>
  </recensione>
  <recensione id="2">
    <username>cliente22</username>
    <codice_gioco>1</codice_gioco>
    <testo>Bello, ma non lo consiglierei</testo>
    <data>2024-03-18</data>
    <giudizi>
      <giudizio>
        <username_votante>cliente2</username_votante>
        <stelle>3</stelle>
      </giudizio>
    </giudizi>
  </recensione>
  <recensione id="3">
    <username>cliente1</username>
    <codice_gioco>1</codice_gioco>
    <testo>recensione 10-06</testo>
    <data>2025-06-10</data>
    <giudizi>
      <giudizio>
        <username_votante>cliente1</username_votante>
        <stelle>4</stelle>
      </giudizio>
    </giudizi>
  </recensione>
</recensioni>
