=== simobe-git/tes/dtd/richieste_gestore.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT richiesteGestore (richiesta+)>
<!ELEMENT richiesta (username, data, status)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT status (#PCDATA)>

=== simobe-git/tes/xml/richieste_gestore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE richiesteGestore SYSTEM "../dtd/richieste_gestore.dtd">
<richiesteGestore>
  <richiesta>
    <username>cliente1</username>
    <data>2025-04-21 15:50:47</data>
    <status>rifiutata</status>
  </richiesta>
  <richiesta>
    <username>cliente1</username>
    <data>2025-04-21 15:54:51</data>
    <status>rifiutata</status>
  </richiesta>
</richiesteGestore>
